name: maraoz
favicon: null
layout_spectrum: 0.8
title: Manuel Araoz homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - name: follow
    item: null
    url: null
